version: "3.1"

services:
  go-api:
    container_name: go-api
    build:
      context: ./go
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    depends_on:
      - postgres
  node-api:
    container_name: node-api
    build:
      context: ./node
      dockerfile: ./Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3002:3000"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    depends_on:
      - postgres
  python-sync-api:
    container_name: python-sync-api
    build:
      context: ./python_sync
      dockerfile: ./Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3003:3000"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    depends_on:
      - postgres
  python-async-api:
    container_name: python-async-api
    build:
      context: ./python_async
      dockerfile: ./Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3004:3000"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: performance-test-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
